### ISSUE TITLE
Research: React component documentation

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-document-viewer-react#16]
We should look for a solution for automated documentation (and demo) generation for our React component packages.

We should check if we can use [Storybook](https://storybook.js.org/) - or search for an alternative solution

##### Tasks
 - [ ] Create documentation for the public components of *sn-document-viewer-react*
 - [ ] Check for for compatibility with Parcel

**Comment by herflis** [comment]
[storybook](https://github.com/storybooks/storybook) seems a possible solution for that but it's webpack4 compatible package is now in alpha state. Should be rechecked if the stable release is out
